// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxS6bYD0WJjgAo3qM8VNGDpM5BeFh6dKo',
    appId: '1:110181583896:web:59bd4f5c8cb83478acc76d',
    messagingSenderId: '110181583896',
    projectId: 'nutracker-29c7f',
    authDomain: 'nutracker-29c7f.firebaseapp.com',
    storageBucket: 'nutracker-29c7f.appspot.com',
    measurementId: 'G-T5DWDV67QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSEO7QWqb1OBE-j-F5LoTjPi1VdOeqVjQ',
    appId: '1:110181583896:android:43c9ab2982b66382acc76d',
    messagingSenderId: '110181583896',
    projectId: 'nutracker-29c7f',
    storageBucket: 'nutracker-29c7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvRWYA0pbMO9AIxkBLR5nSD-7Q7BKADoc',
    appId: '1:110181583896:ios:9337817551698ed4acc76d',
    messagingSenderId: '110181583896',
    projectId: 'nutracker-29c7f',
    storageBucket: 'nutracker-29c7f.appspot.com',
    iosClientId: '110181583896-s3or2e09snbgu5du1n3ob15roq8ddnvb.apps.googleusercontent.com',
    iosBundleId: 'com.example.dart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvRWYA0pbMO9AIxkBLR5nSD-7Q7BKADoc',
    appId: '1:110181583896:ios:9337817551698ed4acc76d',
    messagingSenderId: '110181583896',
    projectId: 'nutracker-29c7f',
    storageBucket: 'nutracker-29c7f.appspot.com',
    iosClientId: '110181583896-s3or2e09snbgu5du1n3ob15roq8ddnvb.apps.googleusercontent.com',
    iosBundleId: 'com.example.dart',
  );
}
